apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

- ./resources/route.yaml

- ./resources/configmap.yaml


commonLabels:
  app.kubernetes.io/part-of: apm-dev-observai
  app.kubernetes.io/managed-by: kustomize

replicas:
- count: 1
  name: pyspark-standalone

patches:
- path: ./patches/deployment-env-patch.yaml
  target:
    kind: Deployment
    group: apps
    version: v1
    name: pyspark-standalone

images:
- name: quay.io/zagaos/pyspark-standalone
  newName: quay.io/zagaos/pyspark-standalone:1.2
  newTag: latest

namePrefix: pyspark-
nameSuffix: -dev

