apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./resources/deployment.yaml
- ./resources/service.yaml
- ./resources/pvc.yaml


commonLabels:
  app.kubernetes.io/part-of: observai
  app.kubernetes.io/managed-by: kustomize