kind: Deployment
apiVersion: apps/v1
metadata:
  name: pyspark-standalone
spec:
  selector:
    matchLabels:
      app: pyspark-standalone
  template:
    spec:
      containers:
        - name: pyspark-standalone
          env:
            - name: AWS_ACCESS_KEY_ID
              value: minioAdmin
            - name: AWS_SECRET_ACCESS_KEY
              value: minio1234
            - name: AWS_REGION
              value: us-east-1
            - name: DISABLE_CERT_CHECKING_SYSTEM_PROPERTY
              value: 'true'
          