replicaCount: 1

ingestion:
  name: ingestion
  container:
    image: 'quay.io/zagaos/ingestion-observai'
    resources:
            requests:
              cpu: 760m
              memory: 1Gi
            limits:
              cpu: 800m
              memory: 2Gi
  env:
            - name: KAFKA_TOPIC_LOG
              valueFrom:
                configMapKeyRef:
                  name: ingestion-configs
                  key: KAFKA_TOPIC_LOG
            - name: KAFKA_TOPIC_TRACE
              valueFrom:
                configMapKeyRef:
                  name: ingestion-configs
                  key: KAFKA_TOPIC_TRACE
            - name: KAFKA_TOPIC_METRIC
              valueFrom:
                configMapKeyRef:
                  name: ingestion-configs
                  key: KAFKA_TOPIC_METRIC
            - name: KAFKA_URL
              valueFrom:
                configMapKeyRef:
                   name: ingestion-configs
                  key: KAFKA_URL
            - name: TRINO_URL
              valueFrom:
                configMapKeyRef:
                  name: ingestion-configs
                  key: TRINO_URL
  config:
      KAFKA_TOPIC_LOG=observai_apm_logs
      KAFKA_TOPIC_TRACE=observai_apm_traces
      KAFKA_TOPIC_METRIC=observai_apm_metrics
      KAFKA_URL=apm-kafka-bootstrap.observability-kafka.svc.cluster.local:9092
      TRINO_URL=jdbc:trino://trino-coordinator-dev.observability-datamesh.svc.cluster.local:8080?SSL=false
