apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: python-app-pipelinerun
spec:
  pipelineRef:
    name: python-app-pipeline
  params:
    - name: GIT-URL
      value: "https://github.com/your/repo.git"
    - name: git-revision
      value: "main"
    - name: github-token
      value: "$(YOUR_GITHUB_TOKEN)"
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: shared-workspace-pvc
