apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: py-demo
  namespace: learning-space
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: py-demo
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleUp:
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      stabilizationWindowSeconds: 300
    scaleDown:
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      stabilizationWindowSeconds: 300      
