apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: py-demo-replica
  labels:
    app: py-demo
    tier: py-demo-replica
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      tier: py-demo-replica
  template:
    metadata:
      labels:
        tier: py-demo-replica
    spec:
      containers:
      - name: py-demo-container
        image: 'docker.io/akashsrivastav1122/demo_images:latest'